### ISSUE TITLE
Review UTS

### ISSUE THREAD

**Issue by johnsihombing42** [hawryyy30/UTS_Lab3_OOPJAVA#1]
Di soal nomor 1, jika ingin lebih baik lagi pada method setter dan getter sebaiknya menambahkan validasi pada parameter yang diberikan. Misalnya, memeriksa apakah password memiliki panjang karakter yang cukup atau tidak, wajib memiliki uppercase, lowercase, dll.

Di soal nomor2, Pada method reverseChar, terdapat double toString(), yaitu new StringBuilder(kata).reverse().toString().toString(). Seharusnya cukup satu saja.

Untuk yang lainnya overall sudah baik dan memenuhi penulisan program yang baik seperti penulisan method yang menggunakan format camelCase, dll.

**Comment by hawryyy30** [comment]
Sudah diperbaiki
Terima kasih,Bang
